name: Test API

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: '1.20'
  
      - name: Build
        working-directory: ./api
        run: go build -v ./...

      - name: Run Go tests
        working-directory: ./api
        run: go test ./...
