name: Go Tests with Docker Compose

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up --detach

      - name: Wait for services to start
        run: sleep 10

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Run Go tests
        run: go test ./api/...

      - name: Stop Docker Compose
        run: docker-compose down
