name: Test API

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Set up Go environment
        run: |
          go env -w GOPROXY=direct
          go env -w GONOSUMDB=*

      - name: Install dependencies
        working-directory: ./api
        run: go mod tidy

      - name: Run Go tests
        working-directory: ./api
        run: go test ./...
